codecov:
  notify:
    after_n_builds: 7
coverage:
  range: 50..95
  round: nearest
  precision: 1
  status:
    project:
      default:
        threshold: 5%
    patch:
      default:
        threshold: 20%
        target: 60%
  ignore:
    - "tests/*"
comment:
  layout: "reach, diff, files"
  behavior: once
  after_n_builds: 7
  require_changes: true
