---
name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 0 * * 1,4"
  workflow_dispatch:
    inputs:
      version:
        description: Manual Unittest Run
        default: test
        required: false

jobs:
  Test:
    name: ${{ matrix.os }}, ${{ matrix.environment-file }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        environment-file:
          - ci/312-oldest.yaml
          - ci/312-latest.yaml
          - ci/313-latest.yaml
          - ci/314-latest.yaml
          - ci/314-dev.yaml
        include:
          - environment-file: ci/314-latest.yaml
            os: macos-15-intel
          - environment-file: ci/314-latest.yaml
            os: macos-latest
          - environment-file: ci/314-latest.yaml
            os: windows-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: ${{ matrix.environment-file }}
          micromamba-version: "latest"

      - name: Install mgwr
        run: |
          pip install .

      - name: Test mgwr
        run: |
          pytest mgwr \
          -v \
          --color yes \
          --cov mgwr \
          --cov-append \
          --cov-report term-missing \
          --cov-report xml \
          --timeout=300

      - name: Codecov
        uses: codecov/codecov-action@v6
